# DigitalOcean App Platform Configuration
name: easy-daily-recipe
services:
- name: web
  source_dir: /
  github:
    repo: your-username/easy-daily-recipe
    branch: main
  run_command: npm run serve
  build_command: npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  health_check:
    http_path: /
    initial_delay_seconds: 10
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3